### ISSUE TITLE
Consider constructing FluentBundle outside FluentElement

### ISSUE THREAD

**Issue by stasm** [wolfadex/fluent-web#10]
Right now, the example shows how to parse translation into a `FluentResource`. The resource is then assign the the Fluent-enable element.

```js
const resource = new FluentResource(`
hello = Hello, Fluent!
`);

const textEl = document.getElementById("my-text-element");
textEl.resource = [
  "en-US",
  resource,
];
```

The resource is then passed internally into the [`FluentBundle` constructor](https://github.com/wolfadex/fluent-web/blob/9c717ffbd45e90e90d21ea27227f940e62cec036/src/index.js#L72), which means that each element ends up having its own bundle.

While bundle objects are mostly lightweight (because they only store references to already parsed `FluentResources`), there are benefits to avoiding creating one bundle per element. I'd suggest letting consumers construct a `FluentBundle` out of the `FluentResources` they need, which has the following advantages:

- The `FluentBundle` constructor takes an optional second parameter which can be used to configure it. See https://projectfluent.org/fluent.js/bundle/classes/fluentbundle.html#constructor.
- One `FluentBundle` instance may link to more than one `FluentResource`. You can for example have a `common.ftl` file with shared transaltions, or a [`branding.ftl`](https://searchfox.org/mozilla-central/source/browser/branding/nightly/locales/en-US/brand.ftl) file with [terms](https://projectfluent.org/fluent/guide/terms.html) which can be referenced from other messages.
- When translations interpolate numbers or dates, the `FluentBundle` instance will create and cache an instance of an `Intl` formatter for the bundle's language, e.g. `Intl.NumberFormat`. By making multiple elements re-use the same instance of `FluentBundle`, you can take advanatge of this caching mechanism.

**Comment by wolfadex** [comment]
Switched to letting the user of the web component create the bundles and pass them in in version 2.0.0. This also addresses #11
