### ISSUE TITLE
Support language fallback

### ISSUE THREAD

**Issue by stasm** [wolfadex/fluent-web#11]
Right now, when a message is missing in one language, the Fluent-enabled element stays empty on the first render, or keeps its previous translation when the language changes. I'd like to suggest supoprting language fallback: when the translation is missing in one language, the element should try to retrieve the translation from the next language, in order of the user's preference stored for instance in `navigator.languages`.

In #10, I suggested switching from letting users construct `FluentResources` to letting them construct `FluentBundles`. To take this idea even futher, you could also allow them to build a sequence of bundles, ordered according to the user's preference.

The sequence could be stored as an array, or as a generator (to defer the cost of parsing fallback languages), or even an async generator (to defer the cost of fetching them). If you want to allow generators, take a look at the `cached-iterable` package which prevents the generator from depleting.

See https://github.com/projectfluent/fluent.js/wiki/React-Bindings for an example of an API which does this (it's sync only, however).

**Comment by wolfadex** [comment]
Switched to letting the user of the web component build the bundles. This also resolves #10.

**Comment by stasm** [comment]
The changes look great, thanks, @wolfadex!
