### ISSUE TITLE
Allow escaping args html

### ISSUE THREAD

**Issue by erosson** [wolfadex/fluent-web#15]
Visit https://wolfadex.github.io/fluent-web/, rename `Carl` to `<b onmouseover=alert(/xss/)>Carl</b>`, and wave your mouse around a bit. The script runs; it probably shouldn't.

[The react implementation doesn't run it](https://projectfluent.org/play/?id=e024d634f9da139d8d150f9ecb403bf6). Its approach to embedding html in translations is [more complex than I first realized](https://github.com/projectfluent/fluent.js/wiki/React-Overlays) - only fully understood it after [experimenting with it](https://repl.it/repls/SteelEsteemedTypes).

I have no strong feelings about copying the official behavior here, but some easy way to escape args strings seems necessary. (Maybe `args` and `unsafeArgs` properties?)

**Comment by wolfadex** [comment]
I've been debating this in my head since I started this project. Where is the line drawn between this package being responsible for escaping user input and how much should the consumer of the package be responsible? I do like your suggestion of defaulting to safe but allowing unsafe.

Do you know what Fluent's approach is on displaying something like bolded text? Would it be something like
```
# ftl file
book-name = { book }
book-by = by
book-author = { name }
```
```html
<fluent-text messageId="book-name" />
<b>
  <fluent-text messageId="book-by" />
</b>
<fluent-text messageId="book-author" />
```
to get: My Book **by** Wolfgang Schuster?

**Comment by erosson** [comment]
Just tried it in @fluent/react:
```
# ftl
book = {$book} <abcxyz>by</abcxyz> {$author}
```
```
# js/react jsx
return (
  <Localized id="book"
    vars={{book: "My Book", author: "Wolfgang Schuster"}}
    elems={{abcxyz: <b />}}>
      <div />
    </Localized>
  )
```

React's html-in-js syntax creates dom-elements. I don't think @fluent/react is creating dom at all, but figuring out where to insert dom you've created and passed to it; `abcxyz` is replaced with `b` above. This wouldn't work for calling from Elm since we can't json-encode html, but accepting dom-elements or strings-as-unsafe-html seems like it'd be fine too with this approach.

[@fluent/dom looks like it has different behavior: builtin whitelisting for safe tags/attributes, with different whitelists for ftl files and variables](https://github.com/projectfluent/fluent.js/wiki/DOM-Overlays). I haven't tried that one myself though.

---

On one hand, I'd hesitate to do things any differently than the fluent devs - I'm sure they've put way more thought into their project's security than I have, and different behavior might confuse users. On the other hand, escaped args are way easier to implement than the official behaviors, and I think it solves my personal concerns for my projects - I'm willing to trust any html in my translation files.

**Comment by wolfadex** [comment]
Asking in the Mozilla chat I was pointed to https://github.com/zbraniecki/fluent-domoverlays-js/wiki/New-Features-(rev-3). 

As a brief aside, it's probably worthwhile to keep an eye on the discussions around this.

Back to the topic at hand I think I'm going to be doing a bit more reading this week(end), try and find some historical contexts about when _you_ should and shouldn't be escaping html. Ideally I'd like the user of a library to be as safe as possible, however I also want them to have as much flexibility as they need. I'm curious how often people are getting localization files from outside sources, vs writing them themselves.

One idea that did come to mind that could be a possibility is an `unsafe` attribute. When absent everything is escaped and when present everything is left as is. In the case of the developer wanting only the user's input escaped, such as in your example of the user typing in malicious code, then the developer would have to do the escaping themselves. This would allow something like
```ftl
hello-name = Hello, <b>{name}</b>!
```
```html
<fluent-text messageId="hello-name" unsafe />
```
```js
textEl.args = { name: "<script>malicious...</script>" }
```
to render as: Hello, **<script>malicious...</script>**! (assuming the developer escaped the user's input).

**Comment by wolfadex** [comment]
I think the suggestion of `args` and `unsafeArgs` is approach I'd like to go with for now. As far as the source string, I think I'd rather leave that as is. My guess is that the source strings will be coming from the app author the vast majority of the time. If time proves me wrong, then I'll change it!

I'll work on this, this weekend

**Comment by erosson** [comment]
> I'll work on this, this weekend

Not to ruin your weekend plans, but I implemented `args/unsafeargs` in my fork a few days ago! Another project of mine didn't want to wait; it was intended as a temporary patch. Since you also think that approach is reasonable long-term, I'll send the PR.
