### ISSUE TITLE
Verification of translations

### ISSUE THREAD

**Issue by wolfadex** [wolfadex/fluent-web#3]
I've added an example of a `select` element but used Google Translate for the Thai and Czech translations. @turboMaCk and @toastal would you be willing to verify the new translations I've added? Or if there's anyone else who's is fluent in either language.

**Comment by turboMaCk** [comment]
czech part is "czeched" :upside_down_face:

**Comment by toastal** [comment]
I'm so bad at being @'d on Github ... I'll check
