### ISSUE TITLE
Thai localization of Intl.DateTimeFormat

### ISSUE THREAD

**Issue by wolfadex** [wolfadex/fluent-web#4]
When selecting the locale `th-TH` the year is displayed as 2563 when I expected to see 2020. I don't speak Thai nor am I familiar enough with Thai culture to know if there's a reason that I should expect to see this. If anyone who is familiar could let me know I'd be most appreciative.

I've seen the same results on Safari, Chromium browsers, and FireFox.

**Comment by turboMaCk** [comment]
@toastal mentioned in https://github.com/wolfadex/fluent-web/pull/2#issue-402534494 that Thailand uses Budhist calendar. Perhaps this is correct behaviour?

**Comment by wolfadex** [comment]
Thanks for pointing that out. I love all this things I learn when working on time and language related things!
