### ISSUE TITLE
Format attributes, too

### ISSUE THREAD

**Issue by stasm** [wolfadex/fluent-web#9]
Right now, `getMessage` only formats the message value:

https://github.com/wolfadex/fluent-web/blob/9c717ffbd45e90e90d21ea27227f940e62cec036/src/index.js#L28

Message attributes should be formatted too, using the same arguments.  You can use the same `errors` array, too. Here's one example of how we do it in `@fluent/dom`:

https://github.com/projectfluent/fluent.js/blob/55d26c15445e81393c332c92db174c50d5d7b61a/fluent-dom/src/localization.js#L215-L235

**Comment by stasm** [comment]
In `@fluent/react` I took a slightly different approach. Rather than format all attributes found in `message.attributes`, I only format attributes explicitly whitelisted in `<Localized attrs={…}>`.

https://github.com/projectfluent/fluent.js/blob/55d26c15445e81393c332c92db174c50d5d7b61a/fluent-react/src/localized.ts#L94-L109

**Comment by wolfadex** [comment]
I will include an attribute whitelist, though I think I'll use the name `attributeWhitelist` as it allows someone unfamiliar with this web component or fluent's documentations to at a quick glance have a decent understanding of what's going on.

**Comment by wolfadex** [comment]
The attribute formatting has been resolved by 0d89396ce191332a54725ce4ff3894193ba04952 and published as v1.0.1.

**Comment by wolfadex** [comment]
Attribute whitelist added in 1a2de281ef15f1fc109862a9894f20ed3fe24dd8
